site_name: My Docs
nav:
  - Home: index.md
  - Elements: elements.md
  - Components: components.md
  - Behaviors: behaviors.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences